### ISSUE TITLE
Points CFJ (call for judgement)

### ISSUE THREAD

**Issue by bookofportals** [hubnomic/hubnomic#9]
@ojacobson argues in a7abb98 that rule -107 calls for the subtraction of points, in this case due to the failure of proposal #7. The rule says that a player "loses points", which could be interpreted as meaning that those points are subtracted from their score, or that they lose any points they have, up to that amount (10 points). I hold the later belief, and therefore CFJ (call for judgement, syn. invoke judgment) the statement "Rule -107 calls for the subtraction of points, even if this would result in a negative value".

Arguments: {The general meaning of "loses" is "be deprived of or cease to have or retain (something)" (Google).}

I move that play resume as normal, allowing players to start new turns (R -102). This requires a simple majority to pass, and I vote FOR. ✅

**Comment by ojacobson** [comment]
I also vote ✅ on allowing play to resume.

**Comment by bwarren2** [comment]
I :white_check_mark: on allowing play to resume.  (As as aside, the presence and utility of the negative integers feel real to me as a mathematician.  I feel I should go to -10.)

**Comment by ojacobson** [comment]
I'd prefer not to be the Judge on this one, since it was my decision that lead to the CFJ in the first place.

I agree with @bwarren2's sense that, if a gain is an increase in the positive direction, a loss is an increase in the negative. However, I can find no common use of the word "loses" which directly supports that belief. The [OED](https://en.oxforddictionaries.com/definition/lose) supports @bookofportals' interpretation.

**Comment by bookofportals** [comment]
The motion allowing play to resume passes by simple majority vote. (3 for, 0 against)

**Comment by bwarren2** [comment]
Have we not presumed the use of the positive _and negative_ integers as a default through course of our rules numbering?  Is there a rule that gives indication otherwise?

**Comment by ojacobson** [comment]
Oh, that's clever.

**Comment by bookofportals** [comment]
We've presumed that it's possible, not that it happens _in this case._

**Comment by bwarren2** [comment]
Are the natural numbers anywhere recognized in the rules?  I only see integers.  It seems exceptional to read a previously-nonexistent numeric category into use.

**Comment by bookofportals** [comment]
What I mean is that a players score can be negative (which rule -105 implies), this rule just can't decrease a score past 0, as you can't lose what you don't have.

**Comment by bwarren2** [comment]
Such a reading immediately raises several difficulties.

It produces transaction ordering concerns in PR resolution.  Without negative numbers, if I am at or near 0, I have an incentive to clear all the PRs I might lose first, then all the PRs I might win.  This occludes incentives and motives in what should be a pure consideration of proposals, or incurs a substantial burden in new rules of transaction orderings.  (Further, it cuts against the intended benefits of an asynchronous system such as our Github.)

Even if the above were not true, a natural analogy is found in money.  If I short a stock, my downside risk is theoretically infinite; I can go to arbitrarily-large amounts of negative-money should the circumstances require it.  Money has a system for reverting people to 0 in the way you describe through bankruptcy, but the negative net worth figures _do exist_ prior to bankruptcy (and such a bankruptcy process is nowhere mentioned in our rules).

Even if _that_ were not true, an ex post reading of numeric type information into an underdefined category would militate for annotating _every_ numeric instance with types.  We have all seen where that road goes.  Should such annotation be required, it only makes sense to employ a default type for all underdefined types.  We have clearly established what our default type is, (and it is not the naturals as described,) so we should use it: points have unsigned integer type.

**Comment by bookofportals** [comment]
By the way, I agree that negatives feel better, and I would probably vote for any proposal to make it that way. I just think that this is the meaning of the word.

**Comment by bookofportals** [comment]
I cede the point. Which resolves this. You can consider my CFJ retracted. But I still feel that this is better on the plain text of the rules. I just hadn't considered those other factors.

**Comment by ojacobson** [comment]
Completely on board with proposing fixing the phrasing to enshrine subtraction as a rule, as soon as I can start a turn. Vote, dammit!

**Comment by bookofportals** [comment]
When I get my turn, I'm planing to remove the rule saying you can only have one turn at a time. Should fix this kind of problem.

**Comment by ojacobson** [comment]
Be my guest.

To resolve a tiny procedural ambiguity, I volunteer to judge this CFJ. I find that rule -107 causes the subtraction of exactly ten points from the score of the author of a failed rule-change proposal, regardless of their score the moment prior.

**Comment by bookofportals** [comment]
It probably ceased being a CFJ when there stopped being a dispute, but good going, just in case.
